### ISSUE TITLE
Installing Via Mops.one

### ISSUE THREAD

**Issue by krpeacock** [NatLabs/http-parser.mo#3]
When trying to add http-parser to my project using `mops add`, it fails with the custom  aviate-labs fields from package-set, for `mo:/json`

Arguably, you're doing a valid approach with the package-set for vessel, but mops doesn't parse the aviate labs ones successfully. Could we add a full `mops.toml` file with dependencies?

**Comment by tomijaga** [comment]
Thanks for reporting the issue!

I found that the problem was caused by a package set in the [motoko-matchers](https://github.com/kritzcreek/motoko-matchers/blob/v1.2.0/package-set.dhall) library that was removed from GitHub.
To fix this, I removed the dependency, updated the vessel config files and published a new release (`v0.1.1`).

You should now be able to install the latest release with this command 
```
mops add https://github.com/NatLabs/http-parser.mo#v0.1.1
```
If it doesn't work, please try clearing the cache with `mops cache clean` and install the package again.

**Comment by krpeacock** [comment]
There's one other tweak - the JSON dependency has changed. Line 246 needs to be updated to 
```
JSON.parse(text())
```

The current `JSON.Parser().parse(text())` is no longer valid

**Comment by tomijaga** [comment]
Thanks for pointing this out.
I've updated that line in the code and pushed a new release (`v0.1.2`)
